# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "dawn-first-project"
client_id = "4b7dc6a0522f85897d4ed509cade96a0"
application_url = "https://human-key-farmers-guard.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://human-key-farmers-guard.trycloudflare.com/auth/callback",
  "https://human-key-farmers-guard.trycloudflare.com/auth/shopify/callback",
  "https://human-key-farmers-guard.trycloudflare.com/api/auth/callback",
  "https://human-key-farmers-guard.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-47271c32.myshopify.com"
